// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	models "kredit-plus/models"

	mock "github.com/stretchr/testify/mock"
)

// CustomerRepository is an autogenerated mock type for the CustomerRepository type
type CustomerRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: cust
func (_m *CustomerRepository) Create(cust models.Konsumen) (models.Konsumen, error) {
	ret := _m.Called(cust)

	var r0 models.Konsumen
	if rf, ok := ret.Get(0).(func(models.Konsumen) models.Konsumen); ok {
		r0 = rf(cust)
	} else {
		r0 = ret.Get(0).(models.Konsumen)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.Konsumen) error); ok {
		r1 = rf(cust)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: cust
func (_m *CustomerRepository) Delete(cust models.Konsumen) (models.Konsumen, error) {
	ret := _m.Called(cust)

	var r0 models.Konsumen
	if rf, ok := ret.Get(0).(func(models.Konsumen) models.Konsumen); ok {
		r0 = rf(cust)
	} else {
		r0 = ret.Get(0).(models.Konsumen)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.Konsumen) error); ok {
		r1 = rf(cust)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields:
func (_m *CustomerRepository) FindAll() ([]models.Konsumen, error) {
	ret := _m.Called()

	var r0 []models.Konsumen
	if rf, ok := ret.Get(0).(func() []models.Konsumen); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Konsumen)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ID
func (_m *CustomerRepository) FindByID(ID int) (models.Konsumen, error) {
	ret := _m.Called(ID)

	var r0 models.Konsumen
	if rf, ok := ret.Get(0).(func(int) models.Konsumen); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Get(0).(models.Konsumen)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: cust
func (_m *CustomerRepository) Update(cust models.Konsumen) (models.Konsumen, error) {
	ret := _m.Called(cust)

	var r0 models.Konsumen
	if rf, ok := ret.Get(0).(func(models.Konsumen) models.Konsumen); ok {
		r0 = rf(cust)
	} else {
		r0 = ret.Get(0).(models.Konsumen)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.Konsumen) error); ok {
		r1 = rf(cust)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCustomerRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewCustomerRepository creates a new instance of CustomerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCustomerRepository(t mockConstructorTestingTNewCustomerRepository) *CustomerRepository {
	mock := &CustomerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
